repos:
  - repo: local
    hooks:
      - id: stylua
        name: StyLua
        language: system
        entry: stylua
        types: [lua]
  - repo: local
    hooks:
      - id: luacheck
        name: Luacheck
        language: system
        entry: luacheck
        args: [
          --std,
          luajit,
          --globals,
          vim,
          --max-line-length,
          '150',
          --no-config,
        ]
        types: [lua]
